/* Each new term in the Fibonacci sequence is generated by adding the previous
 two terms.By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even - valued terms. */

function fibo(limit , fib = [1, 2], ct = 1) {
    if ((limit - 1) !== ct && fib[ct] < 400000 ) {
        let current = fib[ct] + fib[ct - 1]
        // console.log(current) 
        // if(current % 2 === 0){

            fib.push(current)
        // }
        ct += 1
        fibo(limit, fib, ct)
    }
    let even = []
    fib.forEach(e=>{
        if(e % 2 == 0){
            even.push(e)
        }
    })
    let total = 0
    even.forEach(e =>{
        total += e
    })
    return total
}

// console.log

const answer = fibo()

console.log(answer)